// <auto-generated />
using System;
using DotNet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace dotnet_server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250915000000_MakeConsultationClientIdNullable")]
    partial class MakeConsultationClientIdNullable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            new MigrationSnapshot().BuildModel(modelBuilder);
        }

        private sealed class MigrationSnapshot : ApplicationDbContextModelSnapshot
        {
            public new void BuildModel(ModelBuilder modelBuilder) => base.BuildModel(modelBuilder);
        }
    }
}
